version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/alx-intranet_clone/WebstackPortfolio
permissions:
  - object: /home/ubuntu/alx-intranet_clone
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: WebstackPortfolio/scripts/clean_instance.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: WebstackPortfolio/scripts/instance_os_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: WebstackPortfolio/scripts/python_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: WebstackPortfolio/scripts/gunicorn.sh
      timeout: 300
      runas: ubuntu
    - location: WebstackPortfolio/scripts/nginx.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: WebstackPortfolio/scripts/stop_app.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: WebstackPortfolio/scripts/start_app.sh
      timeout: 300
      runas: ubuntu
