version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install virtualenv

  build:
    commands:
      - ./scripts/gunicorn.sh

artifacts:
  files:
    - '**/*'
